from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

from git import Repo
from github import Github, GithubException

from pipeline.audit.logger import AuditLogger
from pipeline.approval.webhook import WebhookListener
from pipeline.config import Config
from pipeline.models import AuditEntry

_PR_PLAN_TITLE = "Pipeline checkpoint 1: implementation plan review"
_PR_CODE_TITLE = "Pipeline checkpoint 2: generated code deploy review"
_COMMIT_PLAN_MSG = "chore(pipeline): add AI-generated implementation plan"
_COMMIT_CODE_MSG = "feat(pipeline): add AI-generated implementation"


class GitHubApproval:
    def __init__(
        self,
        config: Config,
        run_id: str,
        audit_logger: AuditLogger,
        webhook_listener: WebhookListener,
        repo_local_path: str,
    ) -> None:
        self._config = config
        self._run_id = run_id
        self._audit = audit_logger
        self._webhook = webhook_listener
        self._gh = Github(config.GITHUB_TOKEN)
        self._gh_repo = self._gh.get_repo(config.GITHUB_TARGET_REPO)
        self._local_repo = Repo(repo_local_path)
        self._repo_root = Path(repo_local_path)

    def open_plan_pr(self, branch: str, plan_path: str) -> tuple[str, int]:
        """Returns (pr_url, pr_number)."""
        self._checkout_branch(branch)
        dest_rel = "plan.md"
        shutil.copy2(plan_path, str(self._repo_root / dest_rel))
        self._stage_and_commit([dest_rel], _COMMIT_PLAN_MSG)
        self._push(branch)
        pr = self._create_pr(
            head=branch,
            title=_PR_PLAN_TITLE,
            body=self._plan_pr_body(dest_rel),
        )
        self._log_checkpoint_opened(pr.number, "checkpoint_1", pr.html_url)
        return pr.html_url, pr.number

    def open_code_pr(self, branch: str, changed_files: list[str]) -> tuple[str, int]:
        """Returns (pr_url, pr_number)."""
        self._checkout_branch(branch)
        self._stage_and_commit(changed_files, _COMMIT_CODE_MSG)
        self._push(branch)
        pr = self._create_pr(
            head=branch,
            title=_PR_CODE_TITLE,
            body=self._code_pr_body(changed_files),
        )
        self._log_checkpoint_opened(pr.number, "checkpoint_2", pr.html_url)
        return pr.html_url, pr.number

    def wait_for_merge(self, pr_number: int) -> bool:
        # Guard against race: PR may have been merged before the webhook
        # listener registered its event. Check GitHub API first.
        pr = self._gh_repo.get_pull(pr_number)
        if pr.merged:
            self._log_checkpoint_approved(pr_number)
            return True
        merged = self._webhook.wait_for_pr_merge(pr_number)
        if merged:
            self._log_checkpoint_approved(pr_number)
        return merged

    def _checkout_branch(self, branch: str) -> None:
        base = self._config.PIPELINE_BASE_BRANCH
        origin = self._local_repo.remotes.origin
        origin.fetch()
        existing = [h.name for h in self._local_repo.heads]
        if branch in existing:
            self._local_repo.heads[branch].checkout()
        else:
            self._local_repo.create_head(branch, origin.refs[base]).checkout()

    def _stage_and_commit(self, paths: list[str], message: str) -> None:
        existing = [p for p in paths if (self._repo_root / p).exists()]
        if not existing:
            self._local_repo.index.commit(f"{message} [no files written]")
            return
        self._local_repo.index.add(existing)
        self._local_repo.index.commit(message)

    def _push(self, branch: str) -> None:
        self._local_repo.remotes.origin.push(
            refspec=f"{branch}:{branch}", force=False
        )

    def _create_pr(self, head: str, title: str, body: str):  # type: ignore[return]
        try:
            return self._gh_repo.create_pull(
                title=title,
                body=body,
                head=head,
                base=self._config.PIPELINE_BASE_BRANCH,
            )
        except GithubException as exc:
            raise RuntimeError(f"Failed to create PR: {exc.data}") from exc

    @staticmethod
    def _plan_pr_body(plan_path: str) -> str:
        return (
            "## Pipeline: Implementation Plan Review\n\n"
            f"The AI planner has generated an implementation plan at `{plan_path}`.\n\n"
            "**Merge this PR** to approve the plan and allow the pipeline to proceed "
            "to code generation. **Close without merging** to abort the pipeline run."
        )

    @staticmethod
    def _code_pr_body(changed_files: list[str]) -> str:
        file_list = "\n".join(f"- `{f}`" for f in changed_files)
        return (
            "## Pipeline: Generated Code Deploy Review\n\n"
            "The following files were generated by the AI implementer and have "
            "passed all quality gates (ruff, mypy, pytest, bandit):\n\n"
            f"{file_list}\n\n"
            "**Merge this PR** to deploy. **Close without merging** to abort."
        )

    def _log_checkpoint_opened(
        self, pr_number: int, checkpoint: str, pr_url: str
    ) -> None:
        self._audit.log(
            AuditEntry(
                run_id=self._run_id,
                timestamp=datetime.now(timezone.utc).isoformat(),
                event_type="checkpoint_opened",
                payload={
                    "checkpoint": checkpoint,
                    "pr_number": pr_number,
                    "pr_url": pr_url,
                },
            )
        )

    def _log_checkpoint_approved(self, pr_number: int) -> None:
        self._audit.log(
            AuditEntry(
                run_id=self._run_id,
                timestamp=datetime.now(timezone.utc).isoformat(),
                event_type="checkpoint_approved",
                payload={"pr_number": pr_number},
            )
        )